# Generated by Django 4.0.4 on 2022-06-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='durations in munites')),
                ('required_score_to_pass', models.IntegerField(help_text='required score to pass')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('meduim', 'meduim'), ('hard', 'hard')], max_length=6)),
            ],
        ),
    ]
